<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 5,
                '_lft' => 5,
                '_rgt' => 14,
                'parent_id' => NULL,
                'created_at' => '2018-11-12 21:37:03',
                'updated_at' => '2019-07-15 10:27:12',
                'path' => '/setting',
                'redirect' => '/setting/menus',
                'alwaysShow' => 1,
                'name' => '系统设置',
                'meta' => '{"title":"\\u7cfb\\u7edf\\u8bbe\\u7f6e","icon":"setting","noCache":false,"roles":["user"]}',
                'component' => 'layout',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            1 => 
            array (
                'id' => 6,
                '_lft' => 6,
                '_rgt' => 7,
                'parent_id' => 5,
                'created_at' => '2018-11-12 21:55:40',
                'updated_at' => '2019-03-20 13:28:49',
                'path' => 'menus',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => 'menus-manage',
                'meta' => '{"title":"\\u83dc\\u5355\\u8bbe\\u7f6e","icon":null,"noCache":false,"roles":["admin"]}',
                'component' => 'menus',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            2 => 
            array (
                'id' => 7,
                '_lft' => 15,
                '_rgt' => 22,
                'parent_id' => NULL,
                'created_at' => '2018-11-13 12:05:57',
                'updated_at' => '2019-07-15 10:27:25',
                'path' => '/auth',
                'redirect' => '/auth/admin-user',
                'alwaysShow' => 1,
                'name' => '权限管理',
                'meta' => '{"title":"\\u6743\\u9650\\u7ba1\\u7406","icon":"drag","noCache":false,"roles":["admin"]}',
                'component' => 'layout',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            3 => 
            array (
                'id' => 8,
                '_lft' => 16,
                '_rgt' => 17,
                'parent_id' => 7,
                'created_at' => '2018-11-14 10:48:36',
                'updated_at' => '2019-03-20 13:30:50',
                'path' => 'adminUser',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => 'admin-user-manage',
                'meta' => '{"title":"\\u7ba1\\u7406\\u5458\\u7ba1\\u7406","icon":null,"noCache":false,"roles":["admin"]}',
                'component' => 'adminUser',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            4 => 
            array (
                'id' => 9,
                '_lft' => 18,
                '_rgt' => 19,
                'parent_id' => 7,
                'created_at' => '2018-12-10 16:34:51',
                'updated_at' => '2019-09-18 16:42:08',
                'path' => 'permission',
                'redirect' => NULL,
                'alwaysShow' => 0,
                'name' => 'permission-manage',
                'meta' => '{"title":"\\u6743\\u9650\\u7ba1\\u7406","icon":null,"noCache":false,"roles":["admin"]}',
                'component' => 'permission',
                'remark' => NULL,
                'hidden' => 1,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            5 => 
            array (
                'id' => 10,
                '_lft' => 20,
                '_rgt' => 21,
                'parent_id' => 7,
                'created_at' => '2018-12-10 17:07:56',
                'updated_at' => '2019-03-20 13:31:12',
                'path' => 'role',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => 'role-manage',
                'meta' => '{"title":"\\u89d2\\u8272\\u7ba1\\u7406","icon":null,"noCache":false,"roles":["admin"]}',
                'component' => 'role',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            6 => 
            array (
                'id' => 13,
                '_lft' => 8,
                '_rgt' => 9,
                'parent_id' => 5,
                'created_at' => '2019-03-12 11:18:57',
                'updated_at' => '2019-03-20 13:27:44',
                'path' => 'site',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '站点设置',
                'meta' => '{"title":"\\u7ad9\\u70b9\\u8bbe\\u7f6e","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'site',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            7 => 
            array (
                'id' => 14,
                '_lft' => 23,
                '_rgt' => 30,
                'parent_id' => NULL,
                'created_at' => '2019-03-14 10:36:45',
                'updated_at' => '2019-10-28 12:50:12',
                'path' => '/column',
                'redirect' => NULL,
                'alwaysShow' => 1,
                'name' => '栏目设置',
                'meta' => '{"title":"\\u680f\\u76ee\\u8bbe\\u7f6e","icon":"component","noCache":false,"roles":[]}',
                'component' => 'layout',
                'remark' => NULL,
                'hidden' => 0,
                'props' => 1,
                'order' => 2,
                'parameter' => NULL,
            ),
            8 => 
            array (
                'id' => 15,
                '_lft' => 24,
                '_rgt' => 25,
                'parent_id' => 14,
                'created_at' => '2019-03-14 10:41:52',
                'updated_at' => '2019-10-28 12:50:32',
                'path' => 'index',
                'redirect' => NULL,
                'alwaysShow' => 0,
                'name' => '栏目列表',
                'meta' => '{"title":"\\u680f\\u76ee\\u5217\\u8868","icon":null,"noCache":false,"roles":[]}',
                'component' => 'eventType',
                'remark' => NULL,
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            9 => 
            array (
                'id' => 16,
                '_lft' => 26,
                '_rgt' => 27,
                'parent_id' => 14,
                'created_at' => '2019-03-14 16:37:58',
                'updated_at' => '2019-03-20 13:25:37',
                'path' => 'add',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '添加栏目',
                'meta' => '{"title":"\\u6dfb\\u52a0\\u680f\\u76ee","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'columnAddEdit',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            10 => 
            array (
                'id' => 17,
                '_lft' => 28,
                '_rgt' => 29,
                'parent_id' => 14,
                'created_at' => '2019-03-14 16:44:46',
                'updated_at' => '2019-03-20 13:25:27',
                'path' => 'edit/:id',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '修改栏目',
                'meta' => '{"title":"\\u4fee\\u6539\\u680f\\u76ee","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'columnAddEdit',
                'remark' => '',
                'hidden' => 1,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            11 => 
            array (
                'id' => 18,
                '_lft' => 31,
                '_rgt' => 36,
                'parent_id' => NULL,
                'created_at' => '2019-03-15 11:51:38',
                'updated_at' => '2019-09-04 11:43:17',
                'path' => '/ad',
                'redirect' => NULL,
                'alwaysShow' => 1,
                'name' => '广告管理',
                'meta' => '{"title":"\\u5e7f\\u544a\\u7ba1\\u7406","icon":"example","noCache":false,"roles":["user"]}',
                'component' => 'layout',
                'remark' => NULL,
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            12 => 
            array (
                'id' => 19,
                '_lft' => 32,
                '_rgt' => 33,
                'parent_id' => 18,
                'created_at' => '2019-03-15 11:52:51',
                'updated_at' => '2019-03-20 13:27:26',
                'path' => 'adClass',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '广告分类列表',
                'meta' => '{"title":"\\u5e7f\\u544a\\u5206\\u7c7b\\u5217\\u8868","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'adClass',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            13 => 
            array (
                'id' => 20,
                '_lft' => 34,
                '_rgt' => 35,
                'parent_id' => 18,
                'created_at' => '2019-03-15 14:10:54',
                'updated_at' => '2019-03-20 13:27:16',
                'path' => 'ad',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '广告列表',
                'meta' => '{"title":"\\u5e7f\\u544a\\u5217\\u8868","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'ad',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 2,
                'parameter' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                '_lft' => 37,
                '_rgt' => 44,
                'parent_id' => NULL,
                'created_at' => '2019-03-15 17:23:51',
                'updated_at' => '2019-08-16 12:18:59',
                'path' => '/article',
                'redirect' => NULL,
                'alwaysShow' => 1,
                'name' => '文章管理',
                'meta' => '{"title":"\\u6587\\u7ae0\\u7ba1\\u7406","icon":"form","noCache":false,"roles":["user"]}',
                'component' => 'layout',
                'remark' => NULL,
                'hidden' => 1,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            15 => 
            array (
                'id' => 22,
                '_lft' => 38,
                '_rgt' => 39,
                'parent_id' => 21,
                'created_at' => '2019-03-15 17:24:35',
                'updated_at' => '2019-03-20 13:26:18',
                'path' => 'index',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '文章列表',
                'meta' => '{"title":"\\u6587\\u7ae0\\u5217\\u8868","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'article',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            16 => 
            array (
                'id' => 23,
                '_lft' => 40,
                '_rgt' => 41,
                'parent_id' => 21,
                'created_at' => '2019-03-18 09:54:31',
                'updated_at' => '2019-03-20 13:26:54',
                'path' => 'add',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '新增文章',
                'meta' => '{"title":"\\u65b0\\u589e\\u6587\\u7ae0","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'articleAddEdit',
                'remark' => '',
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            17 => 
            array (
                'id' => 24,
                '_lft' => 42,
                '_rgt' => 43,
                'parent_id' => 21,
                'created_at' => '2019-03-18 09:55:41',
                'updated_at' => '2019-03-20 13:26:45',
                'path' => 'edit/:id',
                'redirect' => '',
                'alwaysShow' => 0,
                'name' => '修改文章',
                'meta' => '{"title":"\\u4fee\\u6539\\u6587\\u7ae0","icon":null,"noCache":false,"roles":["user"]}',
                'component' => 'articleAddEdit',
                'remark' => '',
                'hidden' => 1,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
            18 => 
            array (
                'id' => 48,
                '_lft' => 12,
                '_rgt' => 13,
                'parent_id' => 5,
                'created_at' => '2019-08-08 14:59:25',
                'updated_at' => '2019-08-08 14:59:25',
                'path' => 'files',
                'redirect' => NULL,
                'alwaysShow' => 0,
                'name' => '文件管理',
                'meta' => '{"title":"\\u6587\\u4ef6\\u7ba1\\u7406","icon":null,"noCache":false,"roles":[]}',
                'component' => 'files',
                'remark' => NULL,
                'hidden' => 0,
                'props' => 1,
                'order' => 1,
                'parameter' => NULL,
            ),
        ));
        
        
    }
}